const generateImagePath = (name) => `/images/${name}.png`;

const imageNames = [
  "about_us",
  "add_icon",
  "amazon",
  "adobe",
  "audience",
  "beta",
  "blog1",
  "blog2",
  "blog3",
  "blog4",
  "blogdetail",
  "bulb",
  "box",
  "call",
  "canva",
  "ceo",
  "close_button",
  "ceo_profile",
  "client1",
  "client2",
  "client3",
  "client4",
  "client5",
  "client6",
  "client7",
  "client8",
  "client9",
  "clockcontact",
  "codedev_logo",
  "diamond",
  "email",
  "facebook",
  "figma",
  "illustrator",
  "industry",
  "leftarrow",
  "rightarrow",
  "linkedin1",
  "linkedin2",
  "map",
  "message_icon",
  "mission",
  "peoplegroup",
  "photoshop",
  "portfolio1",
  "portfolio2",
  "portfolio3",
  "process1",
  "process2",
  "process3",
  "process4",
  "projectmanagerlogo",
  "remote_icon",
  "resolution",
  "rings",
  "search_icon",
  "service1",
  "service2",
  "service3",
  "slack",
  "spotify",
  "star1",
  "starcontact",
  "stats1",
  "stats2",
  "stats3",
  "member1",
  "member2",
  "member3",
  "member4",
  "member5",
  "member6",
  "member7",
  "member8",
  "tick",
  "tick1",
  "twitter",
  "upload_icon",
  "vision",
  "zapier",
  "zoom",
  "ourprocess",
  "meetclient",
  "serviceicon1",
  "serviceicon2",
  "serviceicon3",
  "pk",
  "phone",
  "mail",
  "servicedetailbanner",
  "plusicon",
  "plus",
  "minus",
  "servicebannericon",
  "blogimg",
  "codewhite",
  "layerwhite",
];

const IMAGES = imageNames.reduce((acc, name) => {
  acc[name.toUpperCase()] = generateImagePath(name);
  return acc;
}, {});

export { IMAGES };
